name: Release Build & Publish

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  OUTPUT_DIR: output

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore src/test.sln
      - run: dotnet build src/test.sln -c Release --no-restore
      - run: mkdir -p ${{ env.OUTPUT_DIR }}
      - run: dotnet pack src/test.sln -c Release --no-build --output ${{ env.OUTPUT_DIR }}
      - run: |
          for pkg in ${{ env.OUTPUT_DIR }}/*.nupkg; do
            dotnet nuget push "$pkg" \
              --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
              --api-key "${{ secrets.GITHUB_TOKEN }}" \
              --skip-duplicate
          done
